### ISSUE TITLE
t_fwAssets broken, problem seems to be in scitran

### ISSUE THREAD

**Issue by DavidBrainard** [ISET/iset3d#14]
I figured out how to get a flywheel token, although I had to infer that the stanfordlabs flywheel instance lives at stanfordlabs.flywheel.io which we not be obvious to most new users.

But, t_fwAssets does not run very far.

>> t_fwAssets
Undefined variable "flywheel" or class "flywheel.Flywheel".

Error in scitran (line 92)
                obj.fw = flywheel.Flywheel(obj.showToken);

Error in t_fwAssets (line 9)
st = scitran('stanfordlabs');
 
>>

**Comment by wandell** [comment]
Lots of things wrong with this one.  I am going to try make a more guided tour of where to go and move all the known broken ones into fixMe or something like that.

**Comment by DavidBrainard** [comment]
Tried the new introductory tutorials.

t_piIntroduction01 - works!
t_piIntroduction02 - works after we installed RDTB!
t_piIntroduction03 - not so much

Our first problem is that scitran needs the flywheel SDK, which I don't think is described in the iset3d dependencies.  We added that, we think.  But the way the flywheel distributes this is a little touchy so it might not be right.  Adding the SDK got us further, but now it crashes out with the following.  Any quick ideas?

>> t_piIntroduction03
Read 5 materials on 6 lines
piGeometryRead starting...
Object:Camera has 0 children object(s) 
piGeometryRead: Saving geometry file scene/PBRT/pbrt-geometry/1_Pyramid.pbrt.
Object:Pyramid has 1 children object(s) 
piGeometryRead: Saving geometry file scene/PBRT/pbrt-geometry/1_Sphere.pbrt.
Object:Sphere has 1 children object(s) 
piGeometryRead: Saving geometry file scene/PBRT/pbrt-geometry/1_ground.pbrt.
Object:ground has 1 children object(s) 
piGeometryRead: Saving geometry file scene/PBRT/pbrt-geometry/1_glass.pbrt.
Object:glass has 1 children object(s) 
piGeometryRead: Saving geometry file scene/PBRT/pbrt-geometry/1_mirror.pbrt.
Object:mirror has 1 children object(s) 
piGeometryRead done.
Saving render recipe as a JSON file /Users/dhb/Documents/MATLAB/toolboxes/iset3d/local/SimpleScene/SimpleScene.json.
Error using flywheel.ApiClient/callApi (line 31)
Java exception occurred:
java.net.UnknownHostException: Warning
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:477)
	at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:153)
	at io.flywheel.rest.HttpsSocketFactory.createSocket(HttpsSocketFactory.java:145)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at io.flywheel.rest.RestClient.callApi(RestClient.java:150)

Error in flywheel.api.DefaultApi/lookupPath (line 397)
            resp = obj.apiClient.callApi('POST', '/lookup', ...

Error in flywheel.Flywheel/lookupPath (line 939)
            [returnData, resp] = obj.defaultApi.lookupPath(varargin{:});

Error in flywheel.Flywheel/lookup (line 1642)
            [returnData, resp] = obj.lookupPath(flywheel.model.ResolverInput('path', split(path, '/')), varargin{:});

Error in piSkymapAdd (line 70)
acquisition = st.fw.lookup('wandell/Graphics assets/data/skymaps');

Error in t_piIntroduction03 (line 44)
[~, skymapInfo] = piSkymapAdd(thisR,'cloudy');
